[[main]]
  name = "About"
  pageRef = "/about_me/"
  weight = 10

[[main]]
  name = "Blog"
  pageRef = "/blog/"
  weight = 20

[[main]]
  name = "Tags"
  pageRef = "/tags/"
  weight = 40

[[social]]
  name = "LinkedIn"
  pre = "fab linkedin"
  url = "https://linkedin.com/in/ellisa-adams"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/ellisa-adams"
  weight = 20

# toml-docs-start sample-navigation
# [[sample]]
#   name = "Blog"
#   pageRef = "/blog/"
#   weight = 10

#[[sample]]
#  name = "Projects"
#  pageRef = "/projects/"
#  weight = 20
#
#[[sample]]
#  name = "Sample project"
#  pageRef = "/projects/sample-project/"
#  parent = "Projects"
#  weight = 1
#
#[[sample]]
#  name = "Another project"
#  pageRef = "/projects/another-project/"
#  parent = "Projects"
#  weight = 2
# toml-docs-end sample-navigation